services:
  nestjs-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - NODE_ENV=development
    volumes:
      - ./src:/usr/src/app/src
  mysql_db:
    image: mysql
    ports:
      - '3307:3307'
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=nestjs_docker_tutorial
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=testuser
      - MYSQL_TCP_PORT=3307
